name: JupyterBook
#name: Build and Publish JupyterBook to GitHub Pages

on:
  push:
    branches: [ main ]

  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
          sudo apt-get install python3-pip
          pip install ghp-import
          pip install jupyter-book
          pip install sphinx_pythia_theme
          pip install sphinxcontrib-applehelp==1.0.4
          pip install sphinxcontrib-bibtex==2.5.0
          pip install sphinxcontrib-devhelp==1.0.2
          pip install sphinxcontrib-htmlhelp==2.0.1
          pip install sphinxcontrib-serializinghtml==1.1.5
          pip install sphinxcontrib-qthelp==1.0.3
          PATH="${PATH}:${HOME}/.local/bin"
          
          
    - name: Show Sphinx version
      run: |
          pip freeze |grep -i sphinx
          pip freeze |grep -i pythia


          
   # - name: Build book TOC file 
   #   run: |
   #     #jupyter-book toc .
    - name: Build book HTML 
      run: |
        jupyter-book build .
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_build/html
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
